apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanning-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scanning-operator
  template:
    metadata:
      labels:
        name: scanning-operator
    spec:
      serviceAccountName: scanning-operator
      containers:
        - name: scanning-operator
          image: quay.io/dedgar/scanning-operator:v0.0.6
          command:
          - scanning-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "scanning-operator"
